FROM php:8.2-apache

RUN docker-php-ext-install mysqli



#########################
#arrancar: sudo docker-compose up -d

#apagar: sudo docker-compose down

#########################
# luego probar FROM:phpmyadmin:5.2-apache
# parece tener apache y phmyadmin todo en uno.
